Simple POST endpoint
vuong-buihv/json-server-rust pull request #14
Opened 2022-02-26 22:49 UTC by nelup20

Closes #9

2022-02-26 22:51 UTC, nelup20 commented on src/main.rs
> +const IP_ADDRESS: &str = "127.0.0.1";
@vuong-buihv Only realized after the previous merge/PR, but won't IP always be localhost/127.0.0.1?
Therefore the user can't change via args (but PORT should definitely be modifiable 👍).

2022-02-27 10:26 UTC, vuong-buihv requested changes

2022-02-27 10:26 UTC, vuong-buihv commented on src/main.rs
> +const IP_ADDRESS: &str = "127.0.0.1";
IP can be modified and be something else than 127.0.0.1

2022-02-27 10:26 UTC, vuong-buihv commented on src/args.rs
> +
The comments /// should be added as they are shown when we do --help or -h

2022-02-27 10:26 UTC, vuong-buihv commented on src/request_methods.rs
> +        return RequestMethods::UNKNOWN;
If it's on the last line then another way to return something in Rust is to just type the thing to return without return and the semicolon

2022-02-27 11:41 UTC, vuong-buihv approved these changes

2022-02-27 11:41 UTC, merged